Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plot_relate(CKD, testK, predict_list, "Age", "Blood Pressure")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_2032/1233680127.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mplot_relate[0m[0;34m([0m[0mCKD[0m[0;34m,[0m [0mtestK[0m[0;34m,[0m [0mpredict_list[0m[0;34m,[0m [0;34m"Age"[0m[0;34m,[0m [0;34m"Blood Pressure"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_2032/1025432811.py[0m in [0;36mplot_relate[0;34m(tbl, test, predict_list, labelx, labely)[0m
[1;32m      7[0m         [0mx[0m [0;34m=[0m [0moriginal_val[0m[0;34m([0m[0mtest[0m[0;34m[[0m[0mlabel[0m[0;34m][0m[0;34m,[0m[0mxmean[0m[0;34m,[0m[0mxstd[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m         [0mtestvals[0m[0;34m=[0m[0mtestvals[0m[0;34m.[0m[0mwith_columns[0m[0;34m([0m[0mlabel[0m[0;34m,[0m[0mx[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m     [0mscatter[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mscatter[0m[0;34m([0m[0mtestvals[0m[0;34m[[0m[0mlabelx[0m[0;34m][0m[0;34m,[0m[0mtestvals[0m[0;34m[[0m[0mlabely[0m[0;34m][0m[0;34m,[0m [0mc[0m[0;34m=[0m[0mtestvals[0m[0;34m[[0m[0;34m'predict'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m     [0mplt[0m[0;34m.[0m[0mxlabel[0m[0;34m([0m[0mlabelx[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m     [0mplt[0m[0;34m.[0m[0mylabel[0m[0;34m([0m[0mlabely[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/datascience/tables.py[0m in [0;36m__getitem__[0;34m(self, index_or_label)[0m
[1;32m    259[0m [0;34m[0m[0m
[1;32m    260[0m     [0;32mdef[0m [0m__getitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mindex_or_label[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 261[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mcolumn[0m[0;34m([0m[0mindex_or_label[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    262[0m [0;34m[0m[0m
[1;32m    263[0m     [0;32mdef[0m [0m__setitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mindex_or_label[0m[0;34m,[0m [0mvalues[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/datascience/tables.py[0m in [0;36mcolumn[0;34m(self, index_or_label)[0m
[1;32m    409[0m                 [0;34m'The column "{}" is not in the table. The table contains '[0m[0;34m[0m[0;34m[0m[0m
[1;32m    410[0m                 [0;34m'these columns: {}'[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 411[0;31m                 [0;34m.[0m[0mformat[0m[0;34m([0m[0mindex_or_label[0m[0;34m,[0m [0;34m', '[0m[0;34m.[0m[0mjoin[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mlabels[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    412[0m             )
[1;32m    413[0m         if (isinstance(index_or_label, int)

[0;31mValueError[0m: The column "Age" is not in the table. The table contains these columns: Class, predict, Blood Pressure, Blood Glucose Random, Hemoglobin, Serum Creatinine
ValueError: The column "Age" is not in the table. The table contains these columns: Class, predict, Blood Pressure, Blood Glucose Random, Hemoglobin, Serum Creatinine

